# -*- coding: utf-8 -*-
"""Day 6 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KUB5h7RT3ViQou9Efs-GMhD68d7TDlUm
"""

def mod_sub(fun): 
  def inner(a, b):
    if a < b:
      a, b = b, a
    fun(a, b)

  return inner

@mod_sub
def sub(a, b):
  print(a - b)

a, b = (int(i) for i in input('Enter two values: ').split())
sub(a, b)