# -*- coding: utf-8 -*-
"""Day 4 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MhnyX2rqHMhMOtAptkibJZe53Mc18scf
"""

# define a function which take a number as argument and return factorial
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)
n=int(input("Input a number to compute the factiorial : "))
print(factorial(n))