# -*- coding: utf-8 -*-
"""Day 3 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18p482Hx35RXBv-soyo7utS0n-EYuTyL1
"""

# from a dictionary print key whose values is maximum in the dictionary
s = 'welcomecoders'
d = {}

for i in s:
    d[i] = d.get(i, 0) + 1
    print(d)

print(d)

res = max(d, key = d.get)
print(res)