# -*- coding: utf-8 -*-
"""Day 1 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tkhqz9qUzTab12w5oUVLlWkxDOW8QhsR
"""

# Enter multiple no and find sum of them

x = [ int(i) for i in input("Enter Multiple Numeric Values : ").split()]
print(sum(x))