# -*- coding: utf-8 -*-
"""Day 2 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FS5ghSdzHrLhZtV4ChN_sMbZJmSCkKiV
"""

s = input("Enter the lottery word : ")

freq = [0]*26

print(freq)
# ASCII code : 97 to 122

for i in s :
    freq[ord(i) - 97] += 1

print(freq)
x = freq.index(max(freq))
print(x)
print(chr(97 + x))