# -*- coding: utf-8 -*-
"""Day 5 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sEUBI-5ITWDchJa9NffN_avbewGVf79A
"""

num = int(input('Enter a number: '))

if num % 3 == 0: # outer if
  if num % 5 == 0:  # inner if
    print('Divisible by both 3 & 5')
  else: #inner else
    print('Divisiblw by 3 but not by 5')
else: # outer else
  if num % 5 == 0:
    print('Divisible by 5 but not by 3')
  else:
    print('Not divisible by 3 & 5')